#!/bin/bash

PROJECT_NAME=${1:-"new-project"}
LOWER_STACK=$(echo "$2" | tr '[:upper:]' '[:lower:]')
STACK=${LOWER_STACK:-"node"}

mkdir $PROJECT_NAME
cd $PROJECT_NAME
git init

echo "# $PROJECT_NAME
A description of \`$PROJECT_NAME\`
" > README.md

echo "# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]
- The entirety of $PROJECT_NAME
" > CHANGELOG.md

mkdir src
mkdir test

function yaml_sub() {
    rm -f final.yml temp.yml  
    ( echo "cat <<EOF >final.yml";
    cat "$1";
    echo "EOF";
    ) >temp.yml
    . temp.yml
    cat final.yml
}

if [ $STACK = node ];
then
    echo "Creating a Node.js Project..."
    node -v > .nvmrc
    npm init -y
    npm install --save-dev mocha chai eslint nyc

    npm install -g json

    json -I -f package.json -e "
    this.scripts.test='mocha --recursive';
    this.scripts.coverage='nyc mocha --recursive';
    this.license='UNLICENSED';
    this.version='0.0.1';
    this.author='Shawn Rushefsky';
    this.main='src/index.js';"

    cat package.json

    curl https://raw.githubusercontent.com/shawnrushefsky/sinit/master/resources/.eslintrc.js > .eslintrc.js

    curl https://raw.githubusercontent.com/github/gitignore/master/Node.gitignore > .gitignore

    touch src/index.js

    mkdir .circleci
    curl https://raw.githubusercontent.com/shawnrushefsky/sinit/master/resources/circle-node.yml > temp.yml
    yaml_sub temp.yml > .circleci/config.yml
fi